FROM node:22-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run test && npm run build


FROM node:22-alpine AS production
WORKDIR /app
COPY package*.json ./
ENV NODE_ENV=production
RUN npm pkg delete scripts.prepare && npm ci --omit=dev && npm cache clean --force
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/certificates ./certificates
EXPOSE 3000
CMD ["node", "dist/src/index.js"]
