services:
  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: vishalmindfiresolutions/node_api:1.1
    restart: unless-stopped
    container_name: nodejs-app-container
    env_file:
      - .env.production
    ports:
      - '${HTTPS_PORT}:4000'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: ${DB_HOST}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
